CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

CREATE TABLE t_accesslink (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created timestamp without time zone NOT NULL,
    userid integer NOT NULL,
    token text NULL,
    CONSTRAINT "PK_t_accesslink" PRIMARY KEY (id)
);

CREATE TABLE t_todo (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    todotext text NULL,
    impact integer NULL,
    priority integer NULL,
    plannedlength integer NULL,
    created timestamp without time zone NOT NULL,
    done timestamp without time zone NULL,
    tags text NULL,
    userid integer NOT NULL,
    parentid integer NULL,
    comment text NULL,
    commentblock text NULL,
    starred boolean NOT NULL,
    deleted boolean NOT NULL,
    fortoday timestamp without time zone NULL,
    deadline timestamp without time zone NULL,
    CONSTRAINT "PK_t_todo" PRIMARY KEY (id)
);

CREATE TABLE t_user (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "UserName" text NULL,
    "Email" text NULL,
    CONSTRAINT "PK_t_user" PRIMARY KEY (id)
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20220920092532_init', '3.1.18');

