CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);


DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220910200807_init') THEN
    CREATE TABLE t_todo (
        id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        todotext text NULL,
        impact integer NULL,
        priority integer NULL,
        plannedlength integer NULL,
        created timestamp without time zone NOT NULL,
        done timestamp without time zone NULL,
        tags text NULL,
        userid text NULL,
        parentid integer NULL,
        comment text NULL,
        CONSTRAINT "PK_t_todo" PRIMARY KEY (id)
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220910200807_init') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20220910200807_init', '3.1.18');
    END IF;
END $$;
